name: tf25_gpu
channels:
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.05.30
  - cudatoolkit=11.7.0
  - cudnn=8.9.2.26
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.9
  - pip=23.1.2
  - python=3.8.16
  - readline=8.2
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - absl-py==0.15.0
    - asteval==0.9.31
    - astunparse==1.6.3
    - cachetools==5.3.1
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - cycler==0.11.0
    - flatbuffers==1.12
    - fonttools==4.40.0
    - future==0.18.3
    - gast==0.4.0
    - google-auth==2.21.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - idna==3.4
    - importlib-metadata==6.7.0
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - llvmlite==0.36.0
    - lmfit==1.2.2
    - markdown==3.4.3
    - markupsafe==2.1.3
    - matplotlib==3.5.2
    - numba==0.53.0
    - numpy==1.19.5
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cudnn-cu11==8.9.2.26
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - packaging==23.1
    - pillow==10.0.0
    - protobuf==3.20.3
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pyparsing==3.1.0
    - python-dateutil==2.8.2
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.8.1
    - six==1.15.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.5.0
    - tensorflow-gpu==2.5.0
    - termcolor==1.1.0
    - tifffile==2023.4.12
    - typing-extensions==3.7.4.3
    - uncertainties==3.1.7
    - urllib3==1.26.16
    - werkzeug==2.3.6
    - wrapt==1.12.1
    - zipp==3.15.0
